// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/agent/api/agent.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateContainerRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// OCI bundle spec, including entrypoint, cmd, env vars, etc.
	// For simplicity, we'll start with just the basics.
	ProcessArgs []string `protobuf:"bytes,2,rep,name=process_args,json=processArgs,proto3" json:"process_args,omitempty"`
	// The path inside the VM where virtio-fs shares the rootfs.
	RootfsPath    string `protobuf:"bytes,3,opt,name=rootfs_path,json=rootfsPath,proto3" json:"rootfs_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_pkg_agent_api_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateContainerRequest) GetProcessArgs() []string {
	if x != nil {
		return x.ProcessArgs
	}
	return nil
}

func (x *CreateContainerRequest) GetRootfsPath() string {
	if x != nil {
		return x.RootfsPath
	}
	return ""
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // e.g., "RUNNING", "FAILED"
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_pkg_agent_api_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_api_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_api_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContainerResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateContainerResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CreateContainerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateContainerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_agent_api_agent_proto protoreflect.FileDescriptor

const file_pkg_agent_api_agent_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/agent/api/agent.proto\x12\x03api\"\x7f\n" +
	"\x16CreateContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12!\n" +
	"\fprocess_args\x18\x02 \x03(\tR\vprocessArgs\x12\x1f\n" +
	"\vrootfs_path\x18\x03 \x01(\tR\n" +
	"rootfsPath\"\x8b\x01\n" +
	"\x17CreateContainerResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2U\n" +
	"\x05Agent\x12L\n" +
	"\x0fCreateContainer\x12\x1b.api.CreateContainerRequest\x1a\x1c.api.CreateContainerResponseB\x18Z\x16micropod/pkg/agent/apib\x06proto3"

var (
	file_pkg_agent_api_agent_proto_rawDescOnce sync.Once
	file_pkg_agent_api_agent_proto_rawDescData []byte
)

func file_pkg_agent_api_agent_proto_rawDescGZIP() []byte {
	file_pkg_agent_api_agent_proto_rawDescOnce.Do(func() {
		file_pkg_agent_api_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_api_agent_proto_rawDesc), len(file_pkg_agent_api_agent_proto_rawDesc)))
	})
	return file_pkg_agent_api_agent_proto_rawDescData
}

var file_pkg_agent_api_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_agent_api_agent_proto_goTypes = []any{
	(*CreateContainerRequest)(nil),  // 0: api.CreateContainerRequest
	(*CreateContainerResponse)(nil), // 1: api.CreateContainerResponse
}
var file_pkg_agent_api_agent_proto_depIdxs = []int32{
	0, // 0: api.Agent.CreateContainer:input_type -> api.CreateContainerRequest
	1, // 1: api.Agent.CreateContainer:output_type -> api.CreateContainerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_agent_api_agent_proto_init() }
func file_pkg_agent_api_agent_proto_init() {
	if File_pkg_agent_api_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_api_agent_proto_rawDesc), len(file_pkg_agent_api_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_api_agent_proto_goTypes,
		DependencyIndexes: file_pkg_agent_api_agent_proto_depIdxs,
		MessageInfos:      file_pkg_agent_api_agent_proto_msgTypes,
	}.Build()
	File_pkg_agent_api_agent_proto = out.File
	file_pkg_agent_api_agent_proto_goTypes = nil
	file_pkg_agent_api_agent_proto_depIdxs = nil
}
